CREATE TABLE IF NOT EXISTS items (
  codigo TEXT PRIMARY KEY,
  sistema_id BIGINT,
  descricao TEXT NOT NULL,
  busca TEXT
);

ALTER TABLE items ADD COLUMN IF NOT EXISTS busca TEXT;
CREATE INDEX IF NOT EXISTS idx_items_busca ON items (busca);

CREATE TABLE IF NOT EXISTS photos (
  codigo TEXT PRIMARY KEY REFERENCES items(codigo) ON DELETE CASCADE,
  url TEXT NOT NULL,
  autor TEXT,
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE photos ADD COLUMN IF NOT EXISTS autor TEXT;

CREATE TABLE IF NOT EXISTS reference_notes (
  codigo TEXT PRIMARY KEY REFERENCES items(codigo) ON DELETE CASCADE,
  note TEXT NOT NULL,
  confidence TEXT NOT NULL,
  img_url TEXT,
  source_site TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS reviews (
  codigo TEXT PRIMARY KEY REFERENCES items(codigo) ON DELETE CASCADE,
  status TEXT NOT NULL,
  reviewed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS duvidas (
  codigo TEXT PRIMARY KEY REFERENCES items(codigo) ON DELETE CASCADE,
  total INT NOT NULL DEFAULT 1,
  ultima_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS fichas (
  codigo TEXT PRIMARY KEY REFERENCES items(codigo) ON DELETE CASCADE,
  nome_arquivo TEXT NOT NULL,
  enviada_em TIMESTAMPTZ NOT NULL DEFAULT now()
);
